spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  main:
    banner-mode: off
  application:
    name: sample-app
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework: error
    org.hibernate: error
    com.m2p: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n"

server:
  servlet:
    context-path: /sample
  port: 8080


